name: Check
on: "push"

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  check:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: "true"
    - run: |
        cargo check --all-targets --all-features

  clippy:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: "true"
    - uses: actions/checkout@v4
    - run: |
        cargo clippy --all-targets --all-features

  check_gen:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: "true"
    - run: |
        go run github.com/norwoodj/helm-docs/cmd/helm-docs@latest --chart-search-root charts
        git add .
        git diff --staged --exit-code
